service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  # profile: placeholder aws permission
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
